apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-notes-app
  template:
    metadata:
      labels:
        app: flask-notes-app
    spec:
      containers:
        - name: flask-notes-app
          image: abukara/flask-notes-app:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-notes-app
spec:
  selector:
    app: flask-notes-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
